/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author charr
 */
public class adidas1 extends javax.swing.JFrame {

    /**
     * Creates new form adidas1
     */
    public adidas1() {
        super("Bienvenidos a tu Store ");
        initComponents();
        this.setSize(500,410);
        this.setLocationRelativeTo(null);
        
    }
    
    public static String textoresultadooculto = "";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CONSULTAR = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        MARCAZAPATO = new javax.swing.JTextField();
        RANGO = new javax.swing.JTextField();
        TALLA = new javax.swing.JTextField();
        TIPO = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        resultadooculto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        CONSULTAR.setBackground(new java.awt.Color(204, 255, 255));
        CONSULTAR.setFont(new java.awt.Font("Yu Gothic Light", 1, 14)); // NOI18N
        CONSULTAR.setForeground(new java.awt.Color(0, 153, 153));
        CONSULTAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        CONSULTAR.setText("CONSULTAR");
        CONSULTAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CONSULTARMouseClicked(evt);
            }
        });
        getContentPane().add(CONSULTAR);
        CONSULTAR.setBounds(150, 300, 180, 60);

        jLabel2.setFont(new java.awt.Font("Yu Gothic Light", 1, 14)); // NOI18N
        jLabel2.setText("ELIGE UNA MARCA DE ZAPATO:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(19, 66, 240, 40);

        jLabel1.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("ADIDAS VELOCES COMO PUMA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 10, 380, 30);

        jLabel4.setFont(new java.awt.Font("Yu Gothic Light", 1, 14)); // NOI18N
        jLabel4.setText("ELIGE TU RANGO PRESUPUESTAL:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 130, 250, 30);

        jLabel5.setFont(new java.awt.Font("Yu Gothic Light", 1, 14)); // NOI18N
        jLabel5.setText("CUENTANOS TU TALLA:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 180, 170, 30);

        jLabel3.setFont(new java.awt.Font("Yu Gothic Light", 1, 14)); // NOI18N
        jLabel3.setText("TIPO DE ZAPATO:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 230, 130, 30);
        getContentPane().add(MARCAZAPATO);
        MARCAZAPATO.setBounds(260, 70, 210, 20);
        getContentPane().add(RANGO);
        RANGO.setBounds(260, 130, 210, 20);
        getContentPane().add(TALLA);
        TALLA.setBounds(260, 180, 210, 20);
        getContentPane().add(TIPO);
        TIPO.setBounds(260, 230, 210, 20);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/zapatoslogo.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 500, 400);
        getContentPane().add(resultadooculto);
        resultadooculto.setBounds(360, 300, 130, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CONSULTARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CONSULTARMouseClicked
        
        switch(this.MARCAZAPATO.getText()){
            case "adidas":
                switch(this.RANGO.getText()){
                    case "100.000 a 150.000":
                        switch(this.TALLA.getText()){
                            case "33":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("ADIDAS Tensaur : 119.000");
                                    case "casual":
                                        this.resultadooculto.setText("ADIDAS Grand Court : 125.000");     
                                }
                            case "34":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("ADIDAS Tensaur : 119.000 ");
                                    case "casual":
                                        this.resultadooculto.setText("ADIDAS Grand Court : 125.000");
                                }
                            case "35":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("ADIDAS Tensaur: 119.000");
                                    case "casual":
                                        this.resultadooculto.setText("ADIDAS Grand Court: 125:000");
                                }
                            case "36":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("ADIDAS Tensaur: 119.000");
                                    case "casual":
                                        this.resultadooculto.setText("ADIDAS Grand Court: 125:000");
                                }
                            case "37":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("ADIDAS Tensaur K: 126.000 ");
                                    case "casual":
                                        this.resultadooculto.setText("ADIDAS Lifestyle: 135.000");
                                }
                            case "38":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("ADIDAS Tensaur K: 127.000");
                                    case "casual":
                                        this.resultadooculto.setText("ADIDAS Lifestyle: 138.000");
                                }
                            case "39":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("ADIDAS Tensaur K: 130.000");
                                    case "casual":
                                        this.resultadooculto.setText("ADIDAS Lifestyle: 140.000");
                                }
                            case "40":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("ADIDAS Run Falcon: 135.000");
                                    case "casual":
                                        this.resultadooculto.setText("ADIDAS Ownthegame: 145.000");
                                }
                            case "41":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("ADIDAS Run Falcon: 140.000");
                                    case "casual":
                                        this.resultadooculto.setText("ADIDAS Ownthegame: 149.000");
                                }
                        }
                    case "150.000 a 200.000":
                        switch(this.TALLA.getText()){
                            case "33":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("ADIDAS Tensaur XS: 152.000");
                                    case "casual":
                                        this.resultadooculto.setText("ADIDAS Run Rush : 157.000");     
                                }
                            case "34":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("ADIDAS Tensaur XS: 155.000");
                                    case "casual":
                                        this.resultadooculto.setText("ADIDAS Run Rush: 160.000");
                                }
                            case "35":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("ADIDAS Tensaur XS: 160.000");
                                    case "casual":
                                        this.resultadooculto.setText("ADIDAS Run Rush: 165.000");
                                }
                            case "36":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("ADIDAS Tensaur XS: 165.000");
                                    case "casual":
                                        this.resultadooculto.setText("ADIDAS Run Rush: 170.000");
                                }
                            case "37":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("ADIDAS Tensaur XS: 170.000");
                                    case "casual":
                                        this.resultadooculto.setText("ADIDAS Run Rush: 175.000");
                                }
                            case "38":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("ADIDAS Tensaur XS: 175.000");
                                    case "casual":
                                        this.resultadooculto.setText("ADIDAS Run Rush: 180.000");
                                }
                            case "39":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("ADIDAS Facon Run Rush: 180.000");
                                    case "casual":
                                        this.resultadooculto.setText("ADIDAS Advantage: 185.000");
                                }
                            case "40":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("ADIDAS Facon Run Rush: 185.000");
                                    case "casual":
                                        this.resultadooculto.setText("ADIDAS Advantage: 190.000");
                                }
                            case "41":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("ADIDAS Facon Run Rush: 190.000");
                                    case "casual":
                                        this.resultadooculto.setText("ADIDAS Advantage: 195.000");
                                }
                        }
                    case "200.000 a 250.000":
                        switch(this.TALLA.getText()){
                            case "33":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("ADIDAS FortaRun Disney: 200.000");
                                    case "casual":
                                        this.resultadooculto.setText("ADIDAS Grand Court Disney : 205.000");     
                                }
                            case "34":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("ADIDAS FortaRun Disney: 205.000");
                                    case "casual":
                                        this.resultadooculto.setText("ADIDAS Grand Court Disney : 210.000");
                                }
                            case "35":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("ADIDAS FortaRun Disney: 210.000");
                                    case "casual":
                                        this.resultadooculto.setText("ADIDAS Grand Court Disney : 215.000");
                                }
                            case "36":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("ADIDAS FortaRun Disney: 215.000");
                                    case "casual":
                                        this.resultadooculto.setText("ADIDAS Grand Court Disney : 220.000");
                                }
                            case "37":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("ADIDAS Lite Racer: 220.000");
                                    case "casual":
                                        this.resultadooculto.setText("ADIDAS Galaxy 5: 225.000");
                                }
                            case "38":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("ADIDAS Lite Racer: 225.000");
                                    case "casual":
                                        this.resultadooculto.setText("ADIDAS Galaxy 5: 230.000");
                                }
                            case "39":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("ADIDAS Lite Racer: 230.000");
                                    case "casual":
                                        this.resultadooculto.setText("ADIDAS Galaxy 5: 235.000");
                                }
                            case "40":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("ADIDAS Lite Racer: 235.000");
                                    case "casual":
                                        this.resultadooculto.setText("ADIDAS Galaxy 5: 240.000");
                                }
                            case "41":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("ADIDAS Lite Racer: 240.000");
                                    case "casual":
                                        this.resultadooculto.setText("ADIDAS Galaxy 5: 245.000");
                                }
                        }
                    case "250.000 a 300.000":
                        switch(this.TALLA.getText()){
                            case "33":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("ADIDAS Tensaur XR: 250.000");
                                    case "casual":
                                        this.resultadooculto.setText("ADIDAS Grand Country: 255.000");     
                                }
                            case "34":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("ADIDAS Tensaur XR: 255.000");
                                    case "casual":
                                        this.resultadooculto.setText("ADIDAS Grand Country: 260.000");
                                }
                            case "35":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("ADIDAS Tensaur XR: 260.000");
                                    case "casual":
                                        this.resultadooculto.setText("ADIDAS Grand Country: 265.000");
                                }
                            case "36":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("ADIDAS Tensaur XR: 265.000");
                                    case "casual":
                                        this.resultadooculto.setText("ADIDAS Grand Country: 270.000");
                                }
                            case "37":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("ADIDAS Tensaur XR: 270.000");
                                    case "casual":
                                        this.resultadooculto.setText("ADIDAS Grand Country: 275.000");
                                }
                            case "38":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("ADIDAS Puremution: 275.000");
                                    case "casual":
                                        this.resultadooculto.setText("ADIDAS Trail Runnig: 280.000");
                                }
                            case "39":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("ADIDAS Puremution: 280.000");
                                    case "casual":
                                        this.resultadooculto.setText("ADIDAS Trail Runnig: 285.000");
                                }
                            case "40":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("ADIDAS Puremution: 285.000");
                                    case "casual":
                                        this.resultadooculto.setText("ADIDAS Trail Runnig: 290.000");
                                }
                            case "41":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("ADIDAS Puremution: 290.000");
                                    case "casual":
                                        this.resultadooculto.setText("ADIDAS Trail Runnig: 295.000");
                                }
                        }
                }
            case "new balance":
                switch(this.RANGO.getText()){
                    case "300.000 a 350.000":
                        switch(this.TALLA.getText()){
                            case "33":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("NB Grade Boy Ravel: 260.000");
                                    case "casual":
                                        this.resultadooculto.setText("NB Kid Shoes 574: 265.000");     
                                }
                            case "34":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("NB Grade Boy Ravel: 270.000");
                                    case "casual":
                                        this.resultadooculto.setText("NB Kid Shoes 574: 275.000");
                                }
                            case "35":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("NB Grade Boy Ravel: 280.000");
                                    case "casual":
                                        this.resultadooculto.setText("NB Kid Shoes 574: 290.000");
                                }
                            case "36":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("NB Grade Boy Ravel: 285.000");
                                    case "casual":
                                        this.resultadooculto.setText("NB Kid Shoes 574: 300.000");
                                }
                            case "37":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("NB Sports Men's 420: 280.000");
                                    case "casual":
                                        this.resultadooculto.setText("NB Men's 570: 320.000");
                                }
                            case "38":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("NB Sports Men's Fresh Floam: 300.000");
                                    case "casual":
                                        this.resultadooculto.setText("NB Men's 574: 330.000");
                                }
                            case "39":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("NB Sports Men's Fresh Floam: 305.000");
                                    case "casual":
                                        this.resultadooculto.setText("NB Men's 574: 335.000");
                                }
                            case "40":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("NB Sports FuelCell Propel V1: 310.000");
                                    case "casual":
                                        this.resultadooculto.setText("NB Men's 997H: 355.000");
                                }
                            case "41":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("NB Sports FuelCell Propel V2: 310.000");
                                    case "casual":
                                        this.resultadooculto.setText("NB Men's 997H: 355.000");
                                }
                        }
                }
            case "nike":
                switch(this.RANGO.getText()){
                    case "200.000 a 250.000":
                        switch(this.TALLA.getText()){
                            case "33":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("Nike Flex Plus: 220.000");
                                    case "casual":
                                        this.resultadooculto.setText("Nike Force 1 LVL8: 230.000");     
                                }
                            case "34":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("Nike Flex Plus: 225.000");
                                    case "casual":
                                        this.resultadooculto.setText("Nike Force 1 LVL8: 235.000");
                                }
                            case "35":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("Nike Flex Plus: 230.000");
                                    case "casual":
                                        this.resultadooculto.setText("Nike Force 1 LVL8: 240.000");
                                }
                            case "36":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("Nike Flex Plus: 235.000");
                                    case "casual":
                                        this.resultadooculto.setText("Nike Force 1 LVL8: 245.000");
                                }
                            case "37":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("Nike Revolution 6 Next Nature: 240.000");
                                    case "casual":
                                        this.resultadooculto.setText("Nike Air Max 97: 240.000");
                                }
                            case "38":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("Nike Revolution 6 Next Nature: 242.900");
                                    case "casual":
                                        this.resultadooculto.setText("Nike Air Max 97: 244.000");
                                }
                            case "39":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("Nike Revolution 6 Next Nature: 243.300");
                                    case "casual":
                                        this.resultadooculto.setText("Nike Air Max 97: 245.000");
                                }
                            case "40":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("Nike Revolution 6 Next Nature: 245.000");
                                    case "casual":
                                        this.resultadooculto.setText("Nike Air Max 97: 246.500");
                                }
                            case "41":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("Nike Revolution 6 Next Nature: 249.900");
                                    case "casual":
                                        this.resultadooculto.setText("Nike Air Max 97: 249.000");
                                }
                        }
                    case "250.000 a 350.000":
                        switch(this.TALLA.getText()){
                            case "33":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("Nike Flex Runner 2: 255.000");
                                    case "casual":
                                        this.resultadooculto.setText("Nike Dunk High: 260.000");     
                                }
                            case "34":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("Nike Flex Runner 2: 265.000");
                                    case "casual":
                                        this.resultadooculto.setText("Nike Dunk High: 275.000");
                                }
                            case "35":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("Nike Flex Runner 2: 275.000");
                                    case "casual":
                                        this.resultadooculto.setText("Nike Dunk High: 285.000");
                                }
                            case "36":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("Nike Flex Runner 2: 285.000");
                                    case "casual":
                                        this.resultadooculto.setText("Nike Dunk High: 300.000");
                                }
                            case "37":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("Nike Revolution 6 FlyEase 4E: 290.000");
                                    case "casual":
                                        this.resultadooculto.setText("Jordan Retro 1 High: 310.000");
                                }
                            case "38":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("Nike Revolution 6 FlyEase 4E: 290.000");
                                    case "casual":
                                        this.resultadooculto.setText("Jordan Retro 1 High: 320.000");
                                }
                            case "39":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("Nike Revolution 6 FlyEase 4E: 290.000");
                                    case "casual":
                                        this.resultadooculto.setText("Jordan Retro 1 High: 330.000");
                                }
                            case "40":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("Nike Revolution 6 FlyEase 4E: 290.000");
                                    case "casual":
                                        this.resultadooculto.setText("Jordan Retro 1 High: 340.000");
                                }
                            case "41":
                                switch(this.TIPO.getText()){
                                    case "deportivo":
                                        this.resultadooculto.setText("Nike Revolution 6 FlyEase 4E: 290.000");
                                    case "casual":
                                        this.resultadooculto.setText("Jordan Retro 1 High: 350.000");
                                }
                        }
                }
        }
        
        textoresultadooculto = resultadooculto.getText();
        
        adidas2 A2 = new adidas2();
        A2.setVisible(true);
        this.dispose();
                
        
    }//GEN-LAST:event_CONSULTARMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adidas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adidas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adidas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adidas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adidas1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CONSULTAR;
    private javax.swing.JTextField MARCAZAPATO;
    private javax.swing.JTextField RANGO;
    private javax.swing.JTextField TALLA;
    private javax.swing.JTextField TIPO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField resultadooculto;
    // End of variables declaration//GEN-END:variables
}
