
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author charr
 */
public class adidas2 extends javax.swing.JFrame {

    /**
     * Creates new form adidas2
     */
    public adidas2() {
        super("Este es!! ");
        initComponents();
        this.setSize(500,410);
        this.setLocationRelativeTo(null);
        
        adidas1 ventana = new adidas1();
        RESULTADO.setText(ventana.textoresultadooculto);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        volver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        RESULTADO = new javax.swing.JTextField();
        COMPRAR = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("ADIDAS VELOCES COMO PUMA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 20, 280, 30);

        volver.setBackground(new java.awt.Color(204, 255, 255));
        volver.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        volver.setForeground(new java.awt.Color(0, 153, 153));
        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/VOLVER.png"))); // NOI18N
        volver.setText("VOLVER");
        volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverMouseClicked(evt);
            }
        });
        getContentPane().add(volver);
        volver.setBounds(20, 290, 220, 60);

        jLabel2.setFont(new java.awt.Font("Yu Gothic Light", 1, 14)); // NOI18N
        jLabel2.setText("TENEMOS:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 160, 80, 30);

        RESULTADO.setBackground(new java.awt.Color(238, 235, 235));
        RESULTADO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESULTADOActionPerformed(evt);
            }
        });
        getContentPane().add(RESULTADO);
        RESULTADO.setBounds(180, 130, 250, 80);

        COMPRAR.setBackground(new java.awt.Color(204, 255, 255));
        COMPRAR.setFont(new java.awt.Font("Yu Gothic Light", 1, 14)); // NOI18N
        COMPRAR.setForeground(new java.awt.Color(0, 153, 153));
        COMPRAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/comprar.png"))); // NOI18N
        COMPRAR.setText("COMPRAR");
        COMPRAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                COMPRARMouseClicked(evt);
            }
        });
        getContentPane().add(COMPRAR);
        COMPRAR.setBounds(260, 290, 220, 60);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/zapatoslogo.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-6, 0, 520, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseClicked
        adidas1 A1 = new adidas1();
        A1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverMouseClicked

    private void COMPRARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_COMPRARMouseClicked
        adidas3 A3= new adidas3();
        A3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_COMPRARMouseClicked

    private void RESULTADOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESULTADOActionPerformed

    }//GEN-LAST:event_RESULTADOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adidas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adidas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adidas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adidas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adidas2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton COMPRAR;
    private javax.swing.JTextField RESULTADO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
